export const TYPE={
    GET_PRODUCTS:'GET_PRODUCTS',
    GET_CATEGORIES:'GET_CATEGORIES',
    SEARCH_FILTER:'SEARCH_FILTER',
    PRICE_FILTER:'PRICE_FILTER',
    CATEGORY_FILTER:'CATEGORY_FILTER',
    RATING_FILTER:'RATING_FILTER',
    CLEAR_FILTER:'CLEAR_FILTER'
    
}