export const TYPE={
    GET_PRODUCTS:'GET_PRODUCTS',
    GET_CATEGORIES:'GET_CATEGORIES',
    SEARCH_FILTER:'SEARCH_FILTER',
    PRICE_FILTER:'PRICE_FILTER',
    CATEGORY_FILTER:'CATEGORY_FILTER',
    ADD_CATEGORY_FILTER:'ADD_CATEGORY_FILTER',
    RATING_FILTER:'RATING_FILTER',
    SORT_BY_PRICE:'SORT_BY_PRICE',
    CLEAR_FILTER:'CLEAR_FILTER',
    ADD_TO_CART:'ADD_TO_CART',
    ADD_TO_WISHLIST:'ADD_TO_WISHLIST'
    
}